[project]
name = "ece228-project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "rdkit>=2025.3.2",
    "torch>=2.7.0",
    "torch-geometric>=2.6.1",
]
